### ISSUE TITLE
error loading block database

### ISSUE THREAD

**Issue by guillaumesoul** [LUX-Core/lux#12]
Hi,

My wallet windows 4.2 stop syncing with network around the 26th july. So i tried to install the latest mercury 5.1 windows wallet and since then, i can't open my 4.2 wallet, i'm having the error error loading block database.

I tried to restore my backup on the 5.1 i got the message can't obtain a lock on data directory users/me/appData/Roaming/Lux luxcore is probably already running. But I don't see anything running.

I downloaded version 5.2.2 but when I restore my wallet I got the following messages :
Unable to bind to 0.0.0.0:26969 on this computer. Luxcore is probably already running.
Failed to listen on any port. Use -listen=0 if you want this.
I tried on windows 7 and mac os X sierra, both OS are giving the same error messages.

How can i get around this?

**Comment by nguyenhoangtran11** [comment]
First of all, I'd like to say that you used the wrong version and you were in the forked chain. So, some of your transaction is invalid when you use newer version.

About "error loading block database", please make sure that you don't have any luxd or lux-qt instance running on your computer by checking the task manager.

Next, please follow this guide to reset completely and fully (https://cdn.discordapp.com/attachments/388703503973089301/473534140843819040/LUX_QT_v5_Win_Mac_User_Guide.pdf)

In order to solve your issue completely, I think you should join our discord channel and ask for the support from our mods. They are working 24/7

Best regards,
Tran
